name: Build

on:
  - push

jobs:
  build_ubuntu:
    runs-on: ubuntu-18.04
    container: gitlab-registry.cern.ch/acts/machines/ubuntu1910
    steps:
    - uses: actions/checkout@v1

    - name: Configure
      run: >
        mkdir build && cd build
        && cmake ..
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_CXX_STANDARD=17
        -DACTS_BUILD_UNITTESTS=ON
        -DCMAKE_CXX_FLAGS="-Werror -fdiagnostics-color=always"
        -DACTS_BUILD_DIGITIZATION_PLUGIN=on
        -DACTS_BUILD_IDENTIFICATION_PLUGIN=on
        -DACTS_BUILD_JSON_PLUGIN=on
        -DACTS_BUILD_BENCHMARKS=on
        -DACTS_BUILD_FATRAS=on
        -DACTS_BUILD_EXAMPLES=on
        -DACTS_BUILD_UNITTESTS=on
        -DACTS_BUILD_LEGACY=on
        -DACTS_BUILD_DD4HEP_PLUGIN=on
        -DACTS_BUILD_TGEO_PLUGIN=on
        -DACTS_BUILD_INTEGRATIONTESTS=on

    - name: Build
      working-directory: build
      run: cmake --build . -- -j$(nproc)

    - name: Unit tests
      working-directory: build
      run: cmake --build . -- test

    - name: Integration tests
      working-directory: build
      run: cmake --build . -- integrationtests

  build_macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
        with:
          path: src

      - name: Install dependencies
        run: >
          cd ..
          && brew install boost eigen cmake xerces-c
          && mkdir deps
          && curl -SL https://acts.web.cern.ch/ACTS/ci/macOS_10.15_deps.tar.gz | tar -xzC deps

      - name: Configure
        run: >
          cd ..
          && source deps/bin/thisroot.sh
          && mkdir build && cd build
          && cmake ../src
          -DCMAKE_PREFIX_PATH=../deps
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_CXX_STANDARD=17
          -DACTS_BUILD_UNITTESTS=ON
          -DCMAKE_CXX_FLAGS="-Werror -fdiagnostics-color=always"
          -DACTS_BUILD_DIGITIZATION_PLUGIN=on
          -DACTS_BUILD_IDENTIFICATION_PLUGIN=on
          -DACTS_BUILD_JSON_PLUGIN=on
          -DACTS_BUILD_BENCHMARKS=on
          -DACTS_BUILD_FATRAS=on
          -DACTS_BUILD_EXAMPLES=on
          -DACTS_BUILD_UNITTESTS=on
          -DACTS_BUILD_LEGACY=on
          -DACTS_BUILD_DD4HEP_PLUGIN=on
          -DACTS_BUILD_TGEO_PLUGIN=on
          -DACTS_BUILD_INTEGRATIONTESTS=on

      - name: Build
        working-directory: ../build
        run: cmake --build . -- -j2

      - name: Unit tests
        working-directory: ../build
        run: cmake --build . -- test

      - name: Integration tests
        working-directory: ../build
        run: cmake --build . -- integrationtests


  build_lcg:
    runs-on: ubuntu-latest
    container: gitlab-registry.cern.ch/acts/machines/${{ matrix.os }}_lcg${{ matrix.lcg }}:latest
    strategy:
      matrix:
        os:
          - cc7
          - slc6
        lcg:
          - 95
          - 96
        exclude:
          - os: slc6
            lcg: 96
    env:
      lcg_map_95: 95apython3
      lcg_map_96: 96
      os_map_cc7: centos7
      os_map_slc6: slc6
    steps:
      - uses: actions/checkout@v1

      # - name: Build on ${{ matrix.os }}, LCG${{ matrix.lcg }}
        # run: .github/workflows/build_job.sh ${{ matrix.lcg }} ${{ matrix.os }}

      - name: Configure
        run: >
          source /opt/lcg/views/LCG_${lcg_map_${{ matrix.lcg }}}/x86_64-${os_map_${{ matrix.os }}}-gcc8-opt/setup.sh
          && mkdir build && cd build
          && cmake ..
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_CXX_STANDARD=17
          -DACTS_BUILD_UNITTESTS=ON
          -DCMAKE_CXX_FLAGS="-Werror -fdiagnostics-color=always"
          -DACTS_BUILD_DIGITIZATION_PLUGIN=on
          -DACTS_BUILD_IDENTIFICATION_PLUGIN=on
          -DACTS_BUILD_JSON_PLUGIN=on
          -DACTS_BUILD_BENCHMARKS=on
          -DACTS_BUILD_FATRAS=on
          -DACTS_BUILD_EXAMPLES=on
          -DACTS_BUILD_UNITTESTS=on
          -DACTS_BUILD_LEGACY=on
          -DACTS_BUILD_DD4HEP_PLUGIN=on
          -DACTS_BUILD_TGEO_PLUGIN=on
          -DACTS_BUILD_INTEGRATIONTESTS=on

      - name: Build
        working-directory: build
        run: >
          source /opt/lcg/views/LCG_${lcg_map_${{ matrix.lcg }}}/x86_64-${os_map_${{ matrix.os }}}-gcc8-opt/setup.sh
          && cmake --build . -- -j$(nproc)

      - name: Unit tests
        working-directory: build
        run: >
          source /opt/lcg/views/LCG_${lcg_map_${{ matrix.lcg }}}/x86_64-${os_map_${{ matrix.os }}}-gcc8-opt/setup.sh
          && cmake --build . -- test

      - name: Integration tests
        working-directory: build
        run: >
          source /opt/lcg/views/LCG_${lcg_map_${{ matrix.lcg }}}/x86_64-${os_map_${{ matrix.os }}}-gcc8-opt/setup.sh
          && cmake --build . -- integrationtests

